<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/delivery.proto

namespace GPBMetadata\Api\V1;

class Delivery
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‡
api/v1/delivery.protoapi.v1";
Request
SentByUserID (
Type (	
UUID (	"5
Email

To (
Subject (	
Content (	"U
RefereeRequest 
request (2.api.v1.Request!

Parameters (2.api.v1.EmailBZtasks/delivery_v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

