<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/delivery.proto

namespace Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Email is a custom message concerned with just Email parameters.
 *
 * Generated from protobuf message <code>api.v1.Email</code>
 */
class Email extends \Google\Protobuf\Internal\Message
{
    /**
     * To is the ID of the user to be sent to
     *
     * Generated from protobuf field <code>int64 To = 1;</code>
     */
    protected $To = 0;
    /**
     * Subject is the Email subject
     *
     * Generated from protobuf field <code>string Subject = 2;</code>
     */
    protected $Subject = '';
    /**
     * Content is the text to be sent in the body of an email
     *
     * Generated from protobuf field <code>string Content = 3;</code>
     */
    protected $Content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $To
     *           To is the ID of the user to be sent to
     *     @type string $Subject
     *           Subject is the Email subject
     *     @type string $Content
     *           Content is the text to be sent in the body of an email
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\Delivery::initOnce();
        parent::__construct($data);
    }

    /**
     * To is the ID of the user to be sent to
     *
     * Generated from protobuf field <code>int64 To = 1;</code>
     * @return int|string
     */
    public function getTo()
    {
        return $this->To;
    }

    /**
     * To is the ID of the user to be sent to
     *
     * Generated from protobuf field <code>int64 To = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->To = $var;

        return $this;
    }

    /**
     * Subject is the Email subject
     *
     * Generated from protobuf field <code>string Subject = 2;</code>
     * @return string
     */
    public function getSubject()
    {
        return $this->Subject;
    }

    /**
     * Subject is the Email subject
     *
     * Generated from protobuf field <code>string Subject = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->Subject = $var;

        return $this;
    }

    /**
     * Content is the text to be sent in the body of an email
     *
     * Generated from protobuf field <code>string Content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Content is the text to be sent in the body of an email
     *
     * Generated from protobuf field <code>string Content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->Content = $var;

        return $this;
    }

}

