<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/delivery.proto

namespace Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * RefereeRequest user request is parsed using this message.
 * Other Unit of Work (UoW) will also embed Request message.
 * Other parameters are then defined is their own field, in this case an Email
 * message
 *
 * Generated from protobuf message <code>api.v1.RefereeRequest</code>
 */
class RefereeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The compulsory common Request message
     *
     * Generated from protobuf field <code>.api.v1.Request request = 1;</code>
     */
    protected $request = null;
    /**
     * Specific parameters that RefereeRequest needs, in this case, Email message
     *
     * Generated from protobuf field <code>.api.v1.Email Parameters = 2;</code>
     */
    protected $Parameters = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Api\V1\Request $request
     *           The compulsory common Request message
     *     @type \Api\V1\Email $Parameters
     *           Specific parameters that RefereeRequest needs, in this case, Email message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\Delivery::initOnce();
        parent::__construct($data);
    }

    /**
     * The compulsory common Request message
     *
     * Generated from protobuf field <code>.api.v1.Request request = 1;</code>
     * @return \Api\V1\Request|null
     */
    public function getRequest()
    {
        return $this->request;
    }

    public function hasRequest()
    {
        return isset($this->request);
    }

    public function clearRequest()
    {
        unset($this->request);
    }

    /**
     * The compulsory common Request message
     *
     * Generated from protobuf field <code>.api.v1.Request request = 1;</code>
     * @param \Api\V1\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Api\V1\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Specific parameters that RefereeRequest needs, in this case, Email message
     *
     * Generated from protobuf field <code>.api.v1.Email Parameters = 2;</code>
     * @return \Api\V1\Email|null
     */
    public function getParameters()
    {
        return $this->Parameters;
    }

    public function hasParameters()
    {
        return isset($this->Parameters);
    }

    public function clearParameters()
    {
        unset($this->Parameters);
    }

    /**
     * Specific parameters that RefereeRequest needs, in this case, Email message
     *
     * Generated from protobuf field <code>.api.v1.Email Parameters = 2;</code>
     * @param \Api\V1\Email $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \Api\V1\Email::class);
        $this->Parameters = $var;

        return $this;
    }

}

