<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/delivery.proto

namespace Api\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request is a common message used by all incoming messages. Typically, you
 * want to embed this in your own custom message. See RefereeRequest.
 *
 * Generated from protobuf message <code>api.v1.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * SentByUserID keeps track of who is sending the message
     *
     * Generated from protobuf field <code>uint64 SentByUserID = 1;</code>
     */
    protected $SentByUserID = 0;
    /**
     * Type tells what kind of UoW it is. They are defined by constants in
     * task/tasks.go and must be followed by all services using this Producer
     * api.
     *
     * Generated from protobuf field <code>string Type = 2;</code>
     */
    protected $Type = '';
    /**
     * UUID defines a unique ID sent by client. We can send it by header
     * request, or as part oj JSON payload.
     * This field is important to ensure deduplication in the event of client
     * retries.
     *
     * Generated from protobuf field <code>string UUID = 3;</code>
     */
    protected $UUID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $SentByUserID
     *           SentByUserID keeps track of who is sending the message
     *     @type string $Type
     *           Type tells what kind of UoW it is. They are defined by constants in
     *           task/tasks.go and must be followed by all services using this Producer
     *           api.
     *     @type string $UUID
     *           UUID defines a unique ID sent by client. We can send it by header
     *           request, or as part oj JSON payload.
     *           This field is important to ensure deduplication in the event of client
     *           retries.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\V1\Delivery::initOnce();
        parent::__construct($data);
    }

    /**
     * SentByUserID keeps track of who is sending the message
     *
     * Generated from protobuf field <code>uint64 SentByUserID = 1;</code>
     * @return int|string
     */
    public function getSentByUserID()
    {
        return $this->SentByUserID;
    }

    /**
     * SentByUserID keeps track of who is sending the message
     *
     * Generated from protobuf field <code>uint64 SentByUserID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSentByUserID($var)
    {
        GPBUtil::checkUint64($var);
        $this->SentByUserID = $var;

        return $this;
    }

    /**
     * Type tells what kind of UoW it is. They are defined by constants in
     * task/tasks.go and must be followed by all services using this Producer
     * api.
     *
     * Generated from protobuf field <code>string Type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Type tells what kind of UoW it is. They are defined by constants in
     * task/tasks.go and must be followed by all services using this Producer
     * api.
     *
     * Generated from protobuf field <code>string Type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * UUID defines a unique ID sent by client. We can send it by header
     * request, or as part oj JSON payload.
     * This field is important to ensure deduplication in the event of client
     * retries.
     *
     * Generated from protobuf field <code>string UUID = 3;</code>
     * @return string
     */
    public function getUUID()
    {
        return $this->UUID;
    }

    /**
     * UUID defines a unique ID sent by client. We can send it by header
     * request, or as part oj JSON payload.
     * This field is important to ensure deduplication in the event of client
     * retries.
     *
     * Generated from protobuf field <code>string UUID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->UUID = $var;

        return $this;
    }

}

