package email

import (
	"encoding/json"
	"io"
)

type Request struct {
	SentByUserID uint64 `json:"sentBy" validate:"required"`
	Type         string `json:"type" validate:"required"`
}

// RefereeRequest user request is parsed into this struct and is different
// from the struct generated by proto compiler.
type RefereeRequest struct {
	Request
	Parameters Email `json:"email" validate:"required"`
}

type Email struct {
	To      uint64 `json:"to"`
	Subject string `json:"subject" validate:"required"`
	Content string `json:"content" validate:"required"`
}

func Bind(body io.ReadCloser, b *RefereeRequest) error {
	return json.NewDecoder(body).Decode(b)
}
